### ISSUE TITLE
bs4.FeatureNotFound

### ISSUE THREAD

**Issue by prabhakaran9397** [prabhakaran9397/auresult#2]
Traceback (most recent call last):
  File "display.py", line 6, in <module>
    soup = BeautifulSoup(page, "lxml")
  File "/usr/local/lib/python2.7/dist-packages/bs4/**init**.py", line 165, in **init**
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
rm: cannot remove '.c0.txt': No such file or directory

**Comment by prabhakaran9397** [comment]
sudo pip install BeautifulSoup4
